### ISSUE TITLE
Unexpected scroll

### ISSUE THREAD

**Issue by k-maciejewski** [etiennebacher/conductor#19]
Hi, first of all, really enjoying the features in `conductor`! However, I notice that when my app steps through the tour, the application scrolls, so that the info "bubble" is at the top of the screen. This seems un-intuitive as the default, since if requires the user to reorient to the app in each step. Is there a simple way to disable this? Do I have to go into the CSS file?

Thanks!!

**Comment by etiennebacher** [comment]
Hello, thanks for using conductor!

I need a bit more info to understand and fix the issue:
* does this happen with the CRAN version or the github version? If it happens with the CRAN version, can you reinstall the github version with `remotes::install_github("etiennebacher/conductor")` and tell me if it works better?
* can you provide a small reproducible example that shows the problem, and explain what you would expect?

I made a small example below. With the github version, when I go to the second step, the application scrolls so that the second plot is entirely highlighted. Is this different from what you want?
```r
library(shiny)
library(conductor)

guide <- Conductor$new()$
  step(
    el = "#first_step",
    "First step"
  )$
  step(
    el = "#second_step",
    "Second step"
  )

ui <- fluidPage(
  useConductor(),
  plotOutput("first_step"),
  br(), br(), br(), br(), br(), br(), br(),
  plotOutput("second_step")
)

server <- function(input, output, session) {
  
  guide$init()$start()
  
  output$first_step <- renderPlot(plot(iris))
  output$second_step <- renderPlot(plot(mtcars))
  
}

shinyApp(ui, server, options = list(launch.browser = TRUE))
```

**Comment by k-maciejewski** [comment]
Hi, thanks for the tip! Using the github version works as expected!

**Comment by etiennebacher** [comment]
Great, I noticed this behavior just after the package was released and I didn't want to resubmit to CRAN just for that. I'll let you know when the new version is on CRAN (probably not so soon if there are not much bug fixes or new features).
